/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/jobs': RouteRecordInfo<
      '/admin/jobs',
      '/admin/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/members': RouteRecordInfo<
      '/admin/members',
      '/admin/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/payrolls': RouteRecordInfo<
      '/admin/payrolls',
      '/admin/payrolls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reports/jobs': RouteRecordInfo<
      '/admin/reports/jobs',
      '/admin/reports/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reports/members': RouteRecordInfo<
      '/admin/reports/members',
      '/admin/reports/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/reports/payrolls': RouteRecordInfo<
      '/admin/reports/payrolls',
      '/admin/reports/payrolls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/timesheets': RouteRecordInfo<
      '/admin/timesheets',
      '/admin/timesheets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logout': RouteRecordInfo<
      '/logout',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/jobs': RouteRecordInfo<
      '/member/jobs',
      '/member/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/payroll_reports': RouteRecordInfo<
      '/member/payroll_reports',
      '/member/payroll_reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/settings': RouteRecordInfo<
      '/member/settings',
      '/member/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/member/timesheets': RouteRecordInfo<
      '/member/timesheets',
      '/member/timesheets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/jobs.vue': {
      routes:
        | '/admin/jobs'
      views:
        | never
    }
    'src/pages/admin/members.vue': {
      routes:
        | '/admin/members'
      views:
        | never
    }
    'src/pages/admin/payrolls.vue': {
      routes:
        | '/admin/payrolls'
      views:
        | never
    }
    'src/pages/admin/reports/jobs.vue': {
      routes:
        | '/admin/reports/jobs'
      views:
        | never
    }
    'src/pages/admin/reports/members.vue': {
      routes:
        | '/admin/reports/members'
      views:
        | never
    }
    'src/pages/admin/reports/payrolls.vue': {
      routes:
        | '/admin/reports/payrolls'
      views:
        | never
    }
    'src/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
    }
    'src/pages/admin/timesheets.vue': {
      routes:
        | '/admin/timesheets'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/logout.vue': {
      routes:
        | '/logout'
      views:
        | never
    }
    'src/pages/member/jobs.vue': {
      routes:
        | '/member/jobs'
      views:
        | never
    }
    'src/pages/member/payroll_reports.vue': {
      routes:
        | '/member/payroll_reports'
      views:
        | never
    }
    'src/pages/member/settings.vue': {
      routes:
        | '/member/settings'
      views:
        | never
    }
    'src/pages/member/timesheets.vue': {
      routes:
        | '/member/timesheets'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
